server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productboard-demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

connector:
  github-api:
    endpointUrl: 'https://api.github.com/orgs/productboard'